### ISSUE TITLE
JPA hibernate dialog issue

### ISSUE THREAD

**Issue by psychology50** [psychology50/trip-tip#2]
```
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.Dialect
    defer-datasource-initialization: true
    database: mysql
```

이전에 스프링 부트를 공부할 때 사용했었던 yml을 참고하면서 초기 세팅을 하는데, 계속해서 dialect 관련 에러가 발생하면서 어플리케이션이 실행이 안 되고 있었다.
방언이 문제니 뭐니 해서 온갖 방법을 다 써보다가 그냥 주석 처리했더니 정상 실행...

Dialect란 건 다양한 DBMS 종류가 있으니 "난 이걸 사용할 거야!"하고 명시해주는 건데, 애초에 이런 Dialect 설정은 Spring Boot가 알아서 잘 지정해주기 때문에 굳이 특수한 이유가 아닌 이상 수동 지정할 필요가 없다.
괜히 잘 모르는데 수동 지정하면 더 심각한 상황인 "실행은 되는데, 잘못 돌아가고 있는 상황"이 연출될 수 있으니 지워두는 게 낫다고 한다.
